# Generated by Django 5.1.7 on 2025-03-17 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_tweet_likes_count_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
